/* Generated By:JavaCC: Do not edit this line. htmlConstants.java */
package HTML;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface htmlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WORD = 5;
  /** RegularExpression Id. */
  int img = 6;
  /** RegularExpression Id. */
  int quote = 7;
  /** RegularExpression Id. */
  int link = 8;
  /** RegularExpression Id. */
  int header = 9;
  /** RegularExpression Id. */
  int para = 10;
  /** RegularExpression Id. */
  int url = 11;
  /** RegularExpression Id. */
  int text = 12;
  /** RegularExpression Id. */
  int color = 13;
  /** RegularExpression Id. */
  int font = 14;
  /** RegularExpression Id. */
  int and = 15;
  /** RegularExpression Id. */
  int alphanumeric = 16;
  /** RegularExpression Id. */
  int epslon = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"ADD\"",
    "\"IMAGE WITH SOURCE\"",
    "\"\\\"\"",
    "\"WITH LINK\"",
    "\"HEADING\"",
    "\"PARAGRAPH\"",
    "\"LINK\"",
    "\"WITH TEXT\"",
    "\"WITH COLOR\"",
    "\"WITH FONT\"",
    "\"AND\"",
    "<alphanumeric>",
    "<epslon>",
  };

}
